[package]
name = "uncommon-lisp"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = true

[dependencies]
lazy_static = "1.5.0"
once_cell = "1.21.3"
